service: config-service

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cloudformation:DescribeStacks
        - cloudformation:ListStacks
      Resource: "*"

functions:
  # Frontend Config
  getFrontendConfig:
    handler: src/handlers/config.getFrontendConfig
    events:
      - http:
          path: /config
          method: get
          cors: true
      - http:
          path: /config.js
          method: get
          cors: true

  # Health Check
  healthCheck:
    handler: src/handlers/health.checkHealth
    events:
      - http:
          path: /health
          method: get
          cors: true

# resources:
#   Outputs:
#     ConfigServiceUrl:
#       Description: Config Service URL
#       Value:
#         Fn::Join:
#           - ""
#           - - "https://"
#             - Ref: RestApi
#             - ".execute-api."
#             - ${self:provider.region}
#             - ".amazonaws.com/"
#             - ${self:provider.stage}
#       Export:
#         Name: ConfigServiceUrl-${self:provider.stage}

plugins:
  - serverless-plugin-typescript