# WebSocket Configuration for OCR Service
# This file contains the WebSocket configuration for different environments

# Development Environment
development:
  websocketEndpoint: "https://xtspcl5cj6.execute-api.us-east-1.amazonaws.com/dev"
  websocketUrl: "wss://xtspcl5cj6.execute-api.us-east-1.amazonaws.com/dev"
  region: "us-east-1"
  cors:
    allowedOrigins:
      - "http://localhost:3000"
      - "http://localhost:3001"
      - "http://localhost:5173"
      - "http://localhost:6100"
      - "http://localhost:6200"
      - "http://localhost:6500"
      - "http://localhost:8080"
    allowedHeaders:
      - "Content-Type"
      - "Authorization"
      - "X-Amz-Date"
      - "X-Api-Key"
      - "X-Amz-Security-Token"
      - "X-Amz-User-Agent"
      - "X-User-Id"
      - "Sec-WebSocket-Protocol"
      - "Sec-WebSocket-Version"
      - "Sec-WebSocket-Key"

# Staging Environment
staging:
  websocketEndpoint: "https://staging-websocket.manpower-platform.com"
  websocketUrl: "wss://staging-websocket.manpower-platform.com"
  region: "us-east-1"
  cors:
    allowedOrigins:
      - "https://staging-admin.manpower-platform.com"
      - "https://staging-applicant.manpower-platform.com"
      - "https://staging-auth.manpower-platform.com"
    allowedHeaders:
      - "Content-Type"
      - "Authorization"
      - "X-Amz-Date"
      - "X-Api-Key"
      - "X-Amz-Security-Token"
      - "X-Amz-User-Agent"
      - "X-User-Id"
      - "Sec-WebSocket-Protocol"
      - "Sec-WebSocket-Version"
      - "Sec-WebSocket-Key"

# Production Environment
production:
  websocketEndpoint: "https://websocket.manpower-platform.com"
  websocketUrl: "wss://websocket.manpower-platform.com"
  region: "us-east-1"
  cors:
    allowedOrigins:
      - "https://admin.manpower-platform.com"
      - "https://applicant.manpower-platform.com"
      - "https://auth.manpower-platform.com"
    allowedHeaders:
      - "Content-Type"
      - "Authorization"
      - "X-Amz-Date"
      - "X-Api-Key"
      - "X-Amz-Security-Token"
      - "X-Amz-User-Agent"
      - "X-User-Id"
      - "Sec-WebSocket-Protocol"
      - "Sec-WebSocket-Version"
      - "Sec-WebSocket-Key"

# WebSocket Connection Settings
connectionSettings:
  # Connection timeout in seconds
  connectionTimeout: 300
  # Message timeout in seconds
  messageTimeout: 30
  # Maximum connections per user
  maxConnectionsPerUser: 5
  # Heartbeat interval in seconds
  heartbeatInterval: 30
  # Reconnection attempts
  maxReconnectionAttempts: 5
  # Reconnection delay in milliseconds
  reconnectionDelay: 5000
  # Ping interval in milliseconds
  pingInterval: 30000

# API Gateway WebSocket Configuration
apiGateway:
  # Route selection expression
  routeSelectionExpression: "$request.body.action"
  # Default route
  defaultRoute: "$default"
  # Connection routes
  connectionRoutes:
    - "$connect"
    - "$disconnect"
    - "$default"
  # Integration timeout in seconds
  integrationTimeout: 30
  # Request timeout in seconds
  requestTimeout: 30

# DynamoDB Configuration for WebSocket
dynamodb:
  # Table name for storing WebSocket connections
  connectionsTable: "ocr-websocket-connections-${stage}"
  # TTL for connection records (in seconds)
  connectionTTL: 3600
  # Batch size for operations
  batchSize: 25

# CloudWatch Logs Configuration
cloudwatch:
  # Log retention in days
  logRetention: 14
  # Log level
  logLevel: "INFO"
  # Enable detailed monitoring
  detailedMonitoring: true

# Security Configuration
security:
  # Enable API key authentication
  apiKeyRequired: false
  # Enable request validation
  requestValidation: true
  # Enable response validation
  responseValidation: true
  # Rate limiting (requests per second)
  rateLimit: 1000
  # Burst limit
  burstLimit: 2000
