name: Test & Quality Checks

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.changes.outputs.frontend }}
      backend: ${{ steps.changes.outputs.backend }}
      aws: ${{ steps.changes.outputs.aws }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            frontend:
              - 'frontend/**'
              - 'package.json'
            backend:
              - 'backend/**'
            aws:
              - 'aws/**'

  test-frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Run type checking
        run: |
          cd frontend
          npx tsc --noEmit

      - name: Run linting
        run: |
          cd frontend
          npm run lint || echo "Linting completed with warnings"

      - name: Run tests (if available)
        run: |
          cd frontend
          if npm run test --if-present; then
            echo "Tests passed"
          else
            echo "No tests found or tests failed"
          fi

      - name: Build application
        run: |
          cd frontend
          npm run build

  test-backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Test backend (placeholder)
        run: |
          echo "🧪 Backend testing placeholder"
          echo "Backend changes detected, would run backend tests here"
          # Add your backend testing logic here

  validate-aws:
    needs: detect-changes
    if: needs.detect-changes.outputs.aws == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'aws/cdk/package-lock.json'

      - name: Install CDK dependencies
        run: |
          cd aws/cdk
          npm ci

      - name: Validate CDK code
        run: |
          cd aws/cdk
          npx tsc --noEmit

      - name: CDK synth (dry run)
        run: |
          cd aws/cdk
          export ENVIRONMENT=test
          export USE_COGNITO=true
          npx cdk synth